
---
title: "Introduction to Open Data Science Chapter 1"
author: "Alfan Mansur"
---

### About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

### Introduction

I am a PhD student in economics at University of Helsinki focusing on **time series econometrics** with emphasis on empirical applications. My current research project is to study the fiscal and monetary policy shocks. 

At the moment, I feel motivated in this course with expectation of learning as much as possible on how to deal with data in a much broader context. I am also eager to learn how to use the open source platforms such as __*R*__ and __*GitHub*__ as well as to improve my programming skills. I firstly heard about this course from my fellows at **Economicum** who told me that it was a great course. I hope I get a great experience as them.

#### My GitHub repository for this project:

https://github.com/alfanmansur/IODS-project

#### My course diary for this project:

https://alfanmansur.github.io/IODS-project

```{r}
# This is a so-called "R chunk" where you can write R code.

date()

```
No text continues here.

